# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""
Interchange export: a generated model as an editable threat-model document.

The point of this renderer is round-tripping. A scan produces a model nobody
drew by hand; exporting it in an interchange format means an architect can open
it in a graphical editor, add the things static analysis cannot see -- the
payment provider, the mainframe, the human with console access -- and feed it
back in through the `manual` ingestor on the next run.

Findings are carried across as threats, so the human sees what the scanner
concluded rather than starting from a blank diagram.

Interoperability note
---------------------
This is an independent implementation written against the observed structure of
the data format. File formats are not copyrightable, and no source code from
any editor implementing this format is incorporated or derived from.
See `docs/INTEROP.md`.
"""

from __future__ import annotations

from datetime import date
from typing import Any, Dict, List, Optional

import yaml

from ..model import Element, Severity, ThreatModel

FORMAT_VERSION = "1.0"

ELEMENT_TYPE = {
    Element.PROCESS: "process",
    Element.DATA_STORE: "data_store",
    Element.EXTERNAL_ENTITY: "external_entity",
}

# STRIDE letter -> the category spelling used by threat-modelling tools.
STRIDE_CATEGORY = {
    "S": "Spoofing", "T": "Tampering", "R": "Repudiation",
    "I": "Information Disclosure", "D": "Denial of Service",
    "E": "Elevation of Privilege",
}

SEVERITY_OUT = {
    Severity.CRITICAL: "critical", Severity.HIGH: "high",
    Severity.MEDIUM: "medium", Severity.LOW: "low", Severity.INFO: "info",
}

# Layout constants. A generated diagram that opens as a pile of overlapping
# boxes is not usable, so nodes are laid out in columns by distance from the
# internet -- which also happens to be the order an attacker traverses them.
COL_WIDTH = 280
ROW_HEIGHT = 130
ORIGIN_X = 80
ORIGIN_Y = 80
MAX_ROWS = 12


def trust_zone_of(model: ThreatModel, asset) -> str:
    """Collapse the boundary hierarchy to the three zones editors understand."""
    if asset.element == Element.EXTERNAL_ENTITY:
        return "external"
    levels = [model.boundaries[b].trust_level
              for b in asset.boundaries if b in model.boundaries]
    if not levels:
        return "internal"
    trust = max(levels)
    if trust <= 10:
        return "external"
    if trust <= 40:
        return "dmz"
    return "internal"


def _positions(model: ThreatModel, assets: List) -> Dict[str, Dict[str, float]]:
    columns: Dict[int, List] = {}
    for a in assets:
        hops = a.facts.get("exposure_hops")
        col = 0 if hops is None else min(int(hops), 8)
        # unreachable assets go to the far right rather than on top of the entry point
        if hops is None:
            col = 9
        columns.setdefault(col, []).append(a)

    out: Dict[str, Dict[str, float]] = {}
    for col in sorted(columns):
        for i, a in enumerate(columns[col]):
            out[a.id] = {
                "x": float(ORIGIN_X + col * COL_WIDTH),
                "y": float(ORIGIN_Y + (i % MAX_ROWS) * ROW_HEIGHT
                           + (i // MAX_ROWS) * 40),
            }
    return out


def render(model: ThreatModel, *, include_findings: bool = True,
           max_findings: int = 300) -> str:
    assets = [a for a in model.assets.values()
              if a.element in ELEMENT_TYPE and a.kind != "Container"]
    # Containers are folded into their workload unless they carry a finding --
    # otherwise a 40-service cluster exports as an unreadable 300-node diagram.
    flagged = {f.component for f in model.active_findings}
    assets += [a for a in model.assets.values()
               if a.kind == "Container" and a.id in flagged]

    pos = _positions(model, assets)
    keep = {a.id for a in assets}

    doc: Dict[str, Any] = {
        "version": FORMAT_VERSION,
        "metadata": {
            "title": f"{model.project} — generated threat model",
            "author": "",
            "created": date.today().isoformat(),
            "modified": date.today().isoformat(),
            "description": (
                f"Generated by ThreatForge from infrastructure-as-code. "
                f"{len(model.assets)} assets, {len(model.flows)} data flows, "
                f"{len(model.active_findings)} evidence-backed findings. "
                f"Edit freely and re-import: hand-added elements are merged with "
                f"the next scan rather than overwritten."),
            "threat_analysis_enabled": True,
        },
        "elements": [],
        "data_flows": [],
        "trust_boundaries": [],
        "threats": [],
    }

    # -- elements ----------------------------------------------------------
    for a in assets:
        el: Dict[str, Any] = {
            "id": a.id,
            "type": ELEMENT_TYPE.get(a.element, "generic"),
            "name": a.name,
            "trust_zone": trust_zone_of(model, a),
            "description": _describe(a),
            "technologies": _technologies(a),
            "position": pos.get(a.id, {"x": float(ORIGIN_X), "y": float(ORIGIN_Y)}),
        }
        tags = sorted(t for t in a.tags if ":" not in t)[:8]
        if tags:
            el["tags"] = tags
        doc["elements"].append(el)

    # -- data flows --------------------------------------------------------
    n = 0
    for f in model.flows:
        if f.source not in keep or f.target not in keep:
            continue
        if f.kind in ("protects", "runs"):        # control edges, not data flows
            continue
        n += 1
        flow: Dict[str, Any] = {
            "id": f"flow-{n}",
            "flow_number": n,
            "name": f.details.get("name") or f.kind.replace("-", " "),
            "from": f.source,
            "to": f.target,
        }
        if f.protocol:
            flow["protocol"] = f.protocol
        if f.encrypted is not None:
            flow["encrypted"] = bool(f.encrypted)
        if f.authenticated is not None:
            flow["authenticated"] = bool(f.authenticated)
        if f.data_classes:
            flow["data"] = sorted(dc.value for dc in f.data_classes)
        if f.crosses_boundary:
            flow["crosses_trust_boundary"] = True
        doc["data_flows"].append(flow)

    # -- trust boundaries ---------------------------------------------------
    for b in sorted(model.boundaries.values(), key=lambda x: x.trust_level):
        members = sorted(m for m in b.members if m in keep)
        if not members:
            continue
        doc["trust_boundaries"].append({
            "id": b.id,
            "name": b.name,
            "description": b.description,
            "trust_level": b.trust_level,
            "contains": members,
        })

    # -- threats ------------------------------------------------------------
    if include_findings:
        for f in model.active_findings[:max_findings]:
            if f.component not in keep:
                continue
            src = f.primary_source
            threat: Dict[str, Any] = {
                "id": f.id,
                "title": f.title,
                "category": (STRIDE_CATEGORY.get(f.stride[0], "Tampering")
                             if f.stride else "Tampering"),
                "element": f.component,
                "severity": SEVERITY_OUT.get(f.risk_level, "medium"),
                "description": " ".join((f.description or "").split()),
                "evidence": [
                    {"description": e.description,
                     "observed": _plain(e.observed),
                     "location": (f"{e.source.file}:{e.source.line}"
                                  if e.source and e.source.file and e.source.line
                                  else (e.source.file if e.source else None))}
                    for e in f.evidence[:4]
                ],
                "risk": {
                    "score": f.risk_score,
                    "likelihood": f.risk.likelihood,
                    "impact": f.risk.impact,
                    "exposure_hops": f.risk.exposure_hops,
                },
                "references": {k: v for k, v in (f.references or {}).items() if v},
                "rule_id": f.rule_id,
            }
            if f.remediation:
                threat["mitigation"] = {
                    "status": "open",
                    "description": f.remediation.summary,
                    "effort": f.remediation.effort,
                }
            doc["threats"].append(threat)

    return yaml.safe_dump(doc, sort_keys=False, allow_unicode=True,
                          default_flow_style=False, width=100)


# ---------------------------------------------------------------------------

def _describe(asset) -> str:
    bits = [asset.display]
    if asset.data_classes:
        bits.append("handles " + ", ".join(sorted(dc.value for dc in asset.data_classes)))
    hops = asset.facts.get("exposure_hops")
    if hops == 0:
        bits.append("untrusted entry point")
    elif hops is not None:
        bits.append(f"{hops} hop(s) from the internet")
    else:
        bits.append("no path from an external entity")
    blast = asset.facts.get("blast_radius")
    if blast:
        bits.append(f"blast radius {blast}")
    return " · ".join(bits)


def _technologies(asset) -> List[str]:
    out: List[str] = []
    for t in asset.tags:
        if t.startswith("image:"):
            image = t.split(":", 1)[1]
            out.append(image.split("/")[-1].split("@")[0])
    if asset.provider and asset.provider not in ("manual", "external"):
        out.append(asset.provider)
    if asset.kind and asset.kind not in ("Container",):
        out.append(asset.kind)
    seen, uniq = set(), []
    for t in out:
        if t and t not in seen:
            seen.add(t)
            uniq.append(t)
    return uniq[:5]


def _plain(value: Any) -> Any:
    """YAML-safe scalars only -- observed values can be sets or enums."""
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    if isinstance(value, (list, tuple, set)):
        return [_plain(v) for v in value]
    if isinstance(value, dict):
        return {str(k): _plain(v) for k, v in value.items()}
    return str(value)
