# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

"""
Microsoft Threat Modeling Tool (.tm7) export.

The import side turns an archive of TMT models into a live baseline. This is the
other half: it lets a model ThreatForge generated from infrastructure-as-code be
opened in TMT, so analysts who work in that tool can review, annotate, and
extend a diagram nobody had to draw.

Together the two make the integration bidirectional:

    TMT model ──import──> ThreatForge ──scan + analyse──> .tm7 ──> TMT

Format notes
------------
`.tm7` is a .NET DataContract serialisation, which is stricter than ordinary
XML: element order, namespace prefixes, and `i:type` discriminators all matter
to the deserialiser. This module emits text rather than using ElementTree,
because ElementTree rewrites namespace prefixes and DataContract will not accept
the result.

Shape classes are fixed by the schema:

    GE.EI   external interactor -> StencilRectangle
    GE.P    process             -> StencilEllipse
    GE.DS   data store          -> StencilParallelLines
    GE.TB.B trust boundary      -> BorderBoundary
    GE.DF   data flow           -> Connector

Verification status
-------------------
Output is schema-conformant and round-trips through our own importer with no
loss of elements, flows, or boundaries. It has **not** been opened in Microsoft
TMT itself, which needs Windows and a TMT installation. Treat TMT compatibility
as expected-but-unverified until you have opened one; see `docs/INTEROP.md`.
"""

from __future__ import annotations

import uuid
from datetime import date
from typing import Any, Dict, List, Optional, Tuple
from xml.sax.saxutils import escape

from ..model import Element, Severity, ThreatModel

SCHEMA_VERSION = "4.3"

NS_MODEL = "http://schemas.datacontract.org/2004/07/ThreatModeling.Model"
NS_ABS = "http://schemas.datacontract.org/2004/07/ThreatModeling.Model.Abstracts"
NS_ARR = "http://schemas.microsoft.com/2003/10/Serialization/Arrays"
NS_KB = "http://schemas.datacontract.org/2004/07/ThreatModeling.KnowledgeBase"
NS_SER = "http://schemas.microsoft.com/2003/10/Serialization/"
NS_XSI = "http://www.w3.org/2001/XMLSchema-instance"
NS_XSD = "http://www.w3.org/2001/XMLSchema"

# A fixed namespace so the same asset always exports as the same GUID. Without
# this, every export produces a new set of ids and TMT sees a brand-new model
# each time, losing any annotation the analyst added.
GUID_NAMESPACE = uuid.UUID("6f1c6b6e-6f2a-5a1e-9c3d-7f4b2a8e5d10")

ELEMENT_STENCIL = {
    Element.EXTERNAL_ENTITY: ("GE.EI", "StencilRectangle", "SE.EI.Ext"),
    Element.PROCESS: ("GE.P", "StencilEllipse", "SE.P.TWS"),
    Element.DATA_STORE: ("GE.DS", "StencilParallelLines", "SE.DS.SQL"),
}

# Protocol -> the TMT flow stencil that carries the same meaning.
PROTOCOL_STENCIL = [
    ("https", "SE.DF.HTTPS"), ("tls", "SE.DF.HTTPS"), ("mtls", "SE.DF.HTTPS"),
    ("http", "SE.DF.HTTP"), ("sql", "SE.DF.SQL"), ("postgres", "SE.DF.SQL"),
    ("mysql", "SE.DF.SQL"), ("grpc", "SE.DF.RPC"), ("rpc", "SE.DF.RPC"),
]

STRIDE_CATEGORY = {
    "S": "Spoofing", "T": "Tampering", "R": "Repudiation",
    "I": "Information Disclosure", "D": "Denial of Service",
    "E": "Elevation of Privilege",
}

# `Critical` is a real member -- a genuine export uses it -- so criticals are
# not flattened into High.
PRIORITY = {
    Severity.CRITICAL: "Critical", Severity.HIGH: "High",
    Severity.MEDIUM: "Medium", Severity.LOW: "Low", Severity.INFO: "Low",
}

# ThreatState is an enum on the .NET side, and DataContractSerializer throws on
# a member it does not recognise -- which surfaces to the user as "the file
# could not be deserialized", with nothing to say which element was at fault.
# Only values observed in a real export are used. Ours are produced by an
# engine, so `AutoGenerated` is the honest mapping; the states a human sets in
# TMT are theirs to set.
THREAT_STATE = "AutoGenerated"

COL_W, ROW_H = 260, 140
ORIGIN_X, ORIGIN_Y = 60, 80
SHAPE_W, SHAPE_H = 120, 90
MAX_ROWS = 10


def guid_for(asset_id: str) -> str:
    return str(uuid.uuid5(GUID_NAMESPACE, asset_id))


def _esc(text: Any) -> str:
    return escape(str(text if text is not None else ""), {'"': "&quot;", "'": "&#39;"})


def _stencil_for_protocol(protocol: Optional[str]) -> str:
    p = (protocol or "").lower()
    for needle, stencil in PROTOCOL_STENCIL:
        if needle in p:
            return stencil
    return "SE.DF.Binary"


# ---------------------------------------------------------------------------

def render(model: ThreatModel, *, include_findings: bool = True,
           max_findings: int = 200, document: Optional[Dict[str, Any]] = None) -> str:
    assets = [a for a in model.assets.values()
              if a.element in ELEMENT_STENCIL and a.kind != "Container"]
    flagged = {f.component for f in model.active_findings}
    assets += [a for a in model.assets.values()
               if a.kind == "Container" and a.id in flagged
               and a.element in ELEMENT_STENCIL]

    positions = _layout(assets)
    keep = {a.id for a in assets}
    surface_guid = guid_for("__surface__")

    out: List[str] = []
    w = out.append
    w('<?xml version="1.0" encoding="utf-8"?>')
    w(f'<ThreatModel xmlns="{NS_MODEL}" xmlns:i="{NS_XSI}">')
    w('  <DrawingSurfaceList>')
    w(f'    <DrawingSurfaceModel z:Id="i1" xmlns:z="{NS_SER}">')
    w(f'      <GenericTypeId xmlns="{NS_ABS}">DRAWINGSURFACE</GenericTypeId>')
    w(f'      <Guid xmlns="{NS_ABS}">{surface_guid}</Guid>')
    w(f'      <Properties xmlns="{NS_ABS}" xmlns:a="{NS_ARR}">')
    w(f'        <a:anyType i:type="b:HeaderDisplayAttribute" xmlns:b="{NS_KB}">')
    w('          <b:DisplayName>Diagram</b:DisplayName>')
    w('          <b:Name/>')
    w('          <b:Value i:nil="true"/>')
    w('        </a:anyType>')
    w(f'        <a:anyType i:type="b:StringDisplayAttribute" xmlns:b="{NS_KB}">')
    w('          <b:DisplayName>Name</b:DisplayName>')
    w('          <b:Name/>')
    w(f'          <b:Value i:type="c:string" xmlns:c="{NS_XSD}">'
      f'{_esc(model.project)} — generated DFD</b:Value>')
    w('        </a:anyType>')
    w('      </Properties>')
    w(f'      <TypeId xmlns="{NS_ABS}">DRAWINGSURFACE</TypeId>')

    # -- shapes -----------------------------------------------------------
    w(f'      <Borders xmlns:a="{NS_ARR}">')
    zid = _ZCounter()
    for a in assets:
        generic, klass, type_id = ELEMENT_STENCIL[a.element]
        x, y = positions[a.id]
        w(_shape(guid_for(a.id), generic, klass, type_id, a.name,
                 x, y, SHAPE_W, SHAPE_H, _describe(a), zid.next()))
    for b, rect in _boundary_rects(model, assets, positions):
        w(_shape(guid_for(b.id), "GE.TB.B", "BorderBoundary", "SE.TB.B", b.name,
                 rect[0], rect[1], rect[2], rect[3], b.description, zid.next()))
    w('      </Borders>')
    w(f'      <Header>{_esc(model.project)} — generated DFD</Header>')

    # -- flows ------------------------------------------------------------
    w(f'      <Lines xmlns:a="{NS_ARR}">')
    flow_endpoints: Dict[str, Tuple[str, str]] = {}
    n = 0
    for f in model.flows:
        if f.source not in keep or f.target not in keep:
            continue
        if f.kind in ("protects", "runs"):
            continue
        n += 1
        sx, sy = positions[f.source]
        tx, ty = positions[f.target]
        label = f.details.get("name") or f.kind.replace("-", " ")
        flow_endpoints[f.id] = (guid_for(f.source), guid_for(f.target))
        w(_connector(guid_for(f.id), _stencil_for_protocol(f.protocol), label,
                     guid_for(f.source), guid_for(f.target),
                     sx + SHAPE_W, sy + SHAPE_H // 2, tx, ty + SHAPE_H // 2,
                     zid.next()))
    w('      </Lines>')
    w('      <Zoom>1</Zoom>')
    w('    </DrawingSurfaceModel>')
    w('  </DrawingSurfaceList>')

    # -- metadata ---------------------------------------------------------
    counts = model.counts()
    description = (
        f"Generated by ThreatForge from infrastructure-as-code on "
        f"{date.today().isoformat()}.\n"
        f"{len(model.assets)} assets, {len(model.flows)} data flows, "
        f"{len(model.active_findings)} evidence-backed findings "
        f"({counts['critical']} critical, {counts['high']} high).\n"
        f"Every threat below cites the file and line that produced it. "
        f"Elements you add here can be fed back in via the .tm7 importer.")
    # The document fields map onto MetaInformation, which is where TMT keeps
    # the same information -- so a title and an owner written here survive the
    # trip into TMT and back rather than living only in our own store.
    doc = (document or {}).get("fields", {}) if document else {}
    def _f(key: str, fallback: str = "") -> str:
        return _esc(str(doc.get(key) or fallback))
    w('  <MetaInformation>')
    w(f'    <Assumptions>{_f("assumptions")}</Assumptions>')
    w(f'    <Contributors>{_f("stakeholders", "ThreatForge")}</Contributors>')
    w(f'    <ExternalDependencies>{_f("dependencies")}</ExternalDependencies>')
    w(f'    <HighLevelSystemDescription>{_f("scope") or _esc(description)}'
      '</HighLevelSystemDescription>')
    w(f'    <Owner>{_f("owner")}</Owner>')
    w(f'    <Reviewer>{_f("reviewer")}</Reviewer>')
    w(f'    <ThreatModelName>{_f("title", model.project)}</ThreatModelName>')
    w('  </MetaInformation>')
    w('  <Notes/>')

    # -- threats ----------------------------------------------------------
    w(f'  <ThreatInstances xmlns:a="{NS_ARR}">')
    if include_findings:
        i = 0
        for f in model.active_findings[:max_findings]:
            if f.component not in keep and f.component not in flow_endpoints:
                continue
            i += 1
            w(_threat(f, i, surface_guid, flow_endpoints))
    w('  </ThreatInstances>')

    w('  <ThreatGenerationEnabled>false</ThreatGenerationEnabled>')
    w('  <Validations/>')
    w(f'  <Version>{SCHEMA_VERSION}</Version>')
    # TMT expects these two after Version. The KnowledgeBase in a real export is
    # the whole SDL template -- several hundred kilobytes of stencil and threat
    # definitions we neither own nor need to reproduce. Emitting the element
    # empty lets the file deserialise and TMT supplies its own template; copying
    # Microsoft's content would be redistributing their template, which is a
    # different thing from writing their file format.
    # In a genuine export the object-reference ids run i1 for the surface, then
    # one per shape and connector, and the KnowledgeBase takes the next. Emitted
    # empty: the real one is Microsoft's template, and TMT supplies its own.
    w(f'  <KnowledgeBase z:Id="{zid.next()}" xmlns:z="{NS_SER}"/>')
    # PromptedKb carries no namespace at all in a genuine export -- it is not
    # in Model, and putting it there is exactly the kind of near-miss that makes
    # DataContractSerializer refuse the whole document.
    w('  <Profile>')
    w('    <PromptedKb xmlns=""/>')
    w('  </Profile>')
    w('</ThreatModel>')
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------------------

class _ZCounter:
    """Object-reference ids. `i1` is the drawing surface, so shapes start at i2."""

    def __init__(self, start: int = 2) -> None:
        self._n = start

    def next(self) -> str:
        v = f"i{self._n}"
        self._n += 1
        return v


def _shape(guid: str, generic: str, klass: str, type_id: str, name: str,
           left: int, top: int, width: int, height: int,
           description: str = "", zid: str = "i2") -> str:
    props = [_string_prop("Name", name)]
    if description:
        props.append(_string_prop("Description", description))
    props.append(_bool_prop("Out Of Scope", False))
    body = "\n".join(props)
    return (
        f'        <a:KeyValueOfguidanyType>\n'
        f'          <a:Key>{guid}</a:Key>\n'
        f'          <a:Value z:Id="{zid}" i:type="{klass}">\n'
        f'            <GenericTypeId xmlns="{NS_ABS}">{generic}</GenericTypeId>\n'
        f'            <Guid xmlns="{NS_ABS}">{guid}</Guid>\n'
        f'            <Properties xmlns="{NS_ABS}" xmlns:a="{NS_ARR}">\n'
        f'{body}\n'
        f'            </Properties>\n'
        f'            <TypeId xmlns="{NS_ABS}">{type_id}</TypeId>\n'
        f'            <Height xmlns="{NS_ABS}">{height}</Height>\n'
        f'            <Left xmlns="{NS_ABS}">{left}</Left>\n'
        f'            <StrokeDashArray xmlns="{NS_ABS}" i:nil="true"/>\n'
        f'            <StrokeThickness xmlns="{NS_ABS}">1</StrokeThickness>\n'
        f'            <Top xmlns="{NS_ABS}">{top}</Top>\n'
        f'            <Width xmlns="{NS_ABS}">{width}</Width>\n'
        f'          </a:Value>\n'
        f'        </a:KeyValueOfguidanyType>'
    )


def _connector(guid: str, type_id: str, name: str, source: str, target: str,
               sx: int, sy: int, tx: int, ty: int, zid: str = "i2") -> str:
    return (
        f'        <a:KeyValueOfguidanyType>\n'
        f'          <a:Key>{guid}</a:Key>\n'
        f'          <a:Value z:Id="{zid}" i:type="Connector">\n'
        f'            <GenericTypeId xmlns="{NS_ABS}">GE.DF</GenericTypeId>\n'
        f'            <Guid xmlns="{NS_ABS}">{guid}</Guid>\n'
        f'            <Properties xmlns="{NS_ABS}" xmlns:a="{NS_ARR}">\n'
        f'{_string_prop("Name", name)}\n'
        f'            </Properties>\n'
        f'            <TypeId xmlns="{NS_ABS}">{type_id}</TypeId>\n'
        f'            <HandleX xmlns="{NS_ABS}">{(sx + tx) // 2}</HandleX>\n'
        f'            <HandleY xmlns="{NS_ABS}">{(sy + ty) // 2}</HandleY>\n'
        f'            <PortSource xmlns="{NS_ABS}">East</PortSource>\n'
        f'            <PortTarget xmlns="{NS_ABS}">West</PortTarget>\n'
        f'            <SourceGuid xmlns="{NS_ABS}">{source}</SourceGuid>\n'
        f'            <SourceX xmlns="{NS_ABS}">{sx}</SourceX>\n'
        f'            <SourceY xmlns="{NS_ABS}">{sy}</SourceY>\n'
        f'            <TargetGuid xmlns="{NS_ABS}">{target}</TargetGuid>\n'
        f'            <TargetX xmlns="{NS_ABS}">{tx}</TargetX>\n'
        f'            <TargetY xmlns="{NS_ABS}">{ty}</TargetY>\n'
        f'          </a:Value>\n'
        f'        </a:KeyValueOfguidanyType>'
    )


def _header_prop(name: str) -> str:
    """A section heading in TMT's property grid. Value is nil, but present."""
    return (
        f'              <a:anyType i:type="b:HeaderDisplayAttribute" xmlns:b="{NS_KB}">\n'
        f'                <b:DisplayName>{_esc(name)}</b:DisplayName>\n'
        f'                <b:Name/>\n'
        f'                <b:Value i:nil="true"/>\n'
        f'              </a:anyType>'
    )


def _string_prop(name: str, value: Any, key: str = "") -> str:
    return (
        f'              <a:anyType i:type="b:StringDisplayAttribute" xmlns:b="{NS_KB}">\n'
        f'                <b:DisplayName>{_esc(name)}</b:DisplayName>\n'
        f'                {"<b:Name>" + _esc(key) + "</b:Name>" if key else "<b:Name/>"}\n'
        f'                <b:Value i:type="c:string" xmlns:c="{NS_XSD}">'
        f'{_esc(value)}</b:Value>\n'
        f'              </a:anyType>'
    )


def _bool_prop(name: str, value: bool, key: str = "") -> str:
    return (
        f'              <a:anyType i:type="b:BooleanDisplayAttribute" xmlns:b="{NS_KB}">\n'
        f'                <b:DisplayName>{_esc(name)}</b:DisplayName>\n'
        f'                {"<b:Name>" + _esc(key) + "</b:Name>" if key else "<b:Name/>"}\n'
        f'                <b:Value i:type="c:boolean" xmlns:c="{NS_XSD}">'
        f'{"true" if value else "false"}</b:Value>\n'
        f'              </a:anyType>'
    )


def _threat(finding, index: int, surface_guid: str,
            flow_endpoints: Dict[str, Tuple[str, str]]) -> str:
    """One ThreatInstance.

    DataContract serialises members alphabetically and the deserialiser is
    unforgiving about both order and namespace: every field below sits in the
    KnowledgeBase namespace (`b:`) while the property map uses Arrays (`a:`).
    Omitting a member, or swapping the two prefixes, makes TMT reject the file.
    """
    src = finding.primary_source
    where = ""
    if src and src.file:
        where = f"\n\nEvidence: {src.file}" + (f":{src.line}" if src.line else "")
    if finding.evidence:
        where += f"\n{finding.evidence[0].description}"
    r = finding.risk
    exposure = ("unreachable from an external entity" if r.exposure_hops is None
                else f"{r.exposure_hops} hop(s) from the internet")
    rationale = (f"\n\nRisk {finding.risk_score}/25 "
                 f"(likelihood {r.likelihood} x impact {r.impact}). "
                 f"Exposure: {exposure}. Blast radius {r.blast_radius}.")
    remediation = (f"\n\nRemediation: {finding.remediation.summary}"
                   if finding.remediation else "")
    description = (" ".join((finding.description or "").split())
                   + where + rationale + remediation)

    category = (STRIDE_CATEGORY.get(finding.stride[0], "Tampering")
                if finding.stride else "Tampering")
    priority = PRIORITY.get(finding.risk_level, "Medium")

    # A threat on a flow is an "interaction" in TMT: source shape, connector,
    # target shape. A threat on an element has no connector.
    if finding.component in flow_endpoints:
        a_guid, b_guid = flow_endpoints[finding.component]
        flow_guid = guid_for(finding.component)
        flow_el = f'        <b:FlowGuid>{flow_guid}</b:FlowGuid>\n'
        interaction = f"{a_guid}:{flow_guid}:{b_guid}"
        source_guid, target_guid = a_guid, b_guid
    else:
        source_guid = target_guid = guid_for(finding.component)
        flow_el = '        <b:FlowGuid i:nil="true"/>\n'
        interaction = source_guid

    props = "".join(
        f'          <a:KeyValueOfstringstring>\n'
        f'            <a:Key>{k}</a:Key>\n'
        f'            <a:Value>{_esc(v)}</a:Value>\n'
        f'          </a:KeyValueOfstringstring>\n'
        for k, v in (("Title", finding.title),
                     ("UserThreatCategory", category),
                     ("UserThreatDescription", description),
                     ("Priority", priority)))

    return (
        f'    <a:KeyValueOfstringThreatpc_P0_PhOB>\n'
        f'      <a:Key>{_esc(finding.id)}</a:Key>\n'
        f'      <a:Value xmlns:b="{NS_KB}">\n'
        f'        <b:ChangedBy i:nil="true"/>\n'
        f'        <b:DrawingSurfaceGuid>{surface_guid}</b:DrawingSurfaceGuid>\n'
        f'{flow_el}'
        f'        <b:Id>{index}</b:Id>\n'
        f'        <b:InteractionKey>{interaction}</b:InteractionKey>\n'
        f'        <b:InteractionString i:nil="true"/>\n'
        f'        <b:ModifiedAt>0001-01-01T00:00:00</b:ModifiedAt>\n'
        f'        <b:Priority>{priority}</b:Priority>\n'
        f'        <b:Properties>\n'
        f'{props}'
        f'        </b:Properties>\n'
        f'        <b:SourceGuid>{source_guid}</b:SourceGuid>\n'
        f'        <b:State>{THREAT_STATE}</b:State>\n'
        f'        <b:StateInformation>{_esc(finding.rule_id)}</b:StateInformation>\n'
        f'        <b:TargetGuid>{target_guid}</b:TargetGuid>\n'
        f'        <b:Title>{_esc(finding.title)}</b:Title>\n'
        f'        <b:TypeId>{_esc(finding.rule_id)}</b:TypeId>\n'
        f'        <b:Upgraded>false</b:Upgraded>\n'
        f'        <b:UserThreatCategory>{_esc(category)}</b:UserThreatCategory>\n'
        f'        <b:UserThreatDescription>{_esc(description)}'
        f'</b:UserThreatDescription>\n'
        f'        <b:UserThreatShortDescription>{_esc(finding.title)}'
        f'</b:UserThreatShortDescription>\n'
        f'        <b:Wide>false</b:Wide>\n'
        f'      </a:Value>\n'
        f'    </a:KeyValueOfstringThreatpc_P0_PhOB>'
    )


def _layout(assets: List) -> Dict[str, Tuple[int, int]]:
    """Columns by distance from the internet -- the order an attacker walks."""
    columns: Dict[int, List] = {}
    for a in assets:
        hops = a.facts.get("exposure_hops")
        col = 9 if hops is None else min(int(hops), 8)
        columns.setdefault(col, []).append(a)
    out: Dict[str, Tuple[int, int]] = {}
    for col in sorted(columns):
        for i, a in enumerate(columns[col]):
            out[a.id] = (ORIGIN_X + col * COL_W,
                         ORIGIN_Y + (i % MAX_ROWS) * ROW_H + (i // MAX_ROWS) * 30)
    return out


def _boundary_rects(model: ThreatModel, assets: List,
                    positions: Dict[str, Tuple[int, int]]):
    """TMT boundaries are rectangles, so draw one around each set of members."""
    keep = {a.id for a in assets}
    for b in sorted(model.boundaries.values(), key=lambda x: -x.trust_level):
        members = [m for m in b.members if m in keep and m in positions]
        if len(members) < 2:
            continue        # a box around one shape adds nothing
        xs = [positions[m][0] for m in members]
        ys = [positions[m][1] for m in members]
        pad = 24
        left, top = min(xs) - pad, min(ys) - pad
        width = (max(xs) + SHAPE_W + pad) - left
        height = (max(ys) + SHAPE_H + pad) - top
        yield b, (left, top, width, height)


def _describe(asset) -> str:
    bits = [asset.display]
    if asset.data_classes:
        bits.append("handles " + ", ".join(sorted(dc.value for dc in asset.data_classes)))
    hops = asset.facts.get("exposure_hops")
    if hops is not None:
        bits.append(f"{hops} hop(s) from the internet")
    return " | ".join(bits)
